name: SnowParticles
version: 1.0
main: com.cptgummiball.snowparticles.SnowParticles
api-version: 1.21
author: CptGummiball
commands:
  snowparticle:
    description: Setze Schneepartikelpunkte
    usage: /snowparticle setpoint <radius> <lowestpoint> <highestpoint>
    permission: snowparticles.admin
